name: Publish Helm Chart to GHCR

on:
  push:
    branches: [ main ]
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - '.github/workflows/helm-release.yml'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Package and Push to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Helm registry login to GHCR
        run: |
          helm registry login ghcr.io \
            --username "${{ github.actor }}" \
            --password "${{ secrets.GITHUB_TOKEN }}"

      - name: Build chart dependencies (if any)
        run: helm dependency build .

      - name: Lint chart
        run: helm lint .

      - name: Package chart
        run: |
          rm -rf dist
          mkdir -p dist
          helm package . --destination dist

      - name: Push chart to GHCR (OCI)
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          CHART_TGZ=$(ls dist/*.tgz)
          helm push "$CHART_TGZ" oci://ghcr.io/$OWNER/charts


